### ISSUE TITLE
CLI options is override when environment is defined

### ISSUE THREAD

**Issue by arantespp** [ttoss/carlin#13]
### Description

When environment options are used, options passed using the CLI are ignored. For instance, if we have:

```yaml
// carlin.yml
environments:
  Production:
    option: some-value
```

and we execute the command `carlin deploy -e Production --option other-value`, the final value for `option` is `some-value`.
